# Generated by Django 4.2.4 on 2023-08-08 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import newsapp.articles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=2000)),
                ('category', models.CharField(choices=[('General crimes', 'General crimes'), ('Good news', 'Good news'), ('Politics', 'Politics'), ('Local News', 'Local News'), ('Street reporters', 'Street reporters')], max_length=16)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('header_image', models.ImageField(blank=True, default='images/img_1_horizontal.jpg', null=True, upload_to='images/', validators=[newsapp.articles.models.MaxImageSizeValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
