# Generated by Django 4.2.4 on 2023-08-10 19:42

from django.conf import settings
from django.db import migrations, models
import newsapp.articles.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0005_alter_article_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(newsapp.articles.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
