# Generated by Django 4.2.4 on 2023-08-10 20:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import newsapp.web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=500)),
                ('category', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=4)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[newsapp.web.models.validate_only_numbers], verbose_name=django.core.validators.MinLengthValidator(10))),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
