# Generated by Django 4.2.4 on 2023-08-10 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 20, 25, 52, 52080, tzinfo=datetime.timezone.utc)),
        ),
    ]
