# Generated by Django 4.2.4 on 2023-08-10 20:29

import datetime
import django.core.validators
from django.db import migrations, models
import newsapp.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_ads_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 17, 20, 29, 1, 470659, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ads',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10), newsapp.web.models.validate_only_numbers]),
        ),
    ]
